name: Tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
  DEPLOY_USER: ${{ vars.DEPLOY_USER }}
  DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

jobs:
  test3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          ls -la ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ls -la ~/.ssh/

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 --version
          pip3 install -r requirements.txt

      - name: Run Tests
        run: ./bin/tests.sh

      - name: Deploy
        run: ./bin/deploy.sh
